services:
  - type: web
    name: wanderly-vietnam
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: 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
        sync: false
